env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/base
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:vue/essential
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - eslint-config-prettier
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser:
    ts: '@typescript-eslint/parser'
    <template>: 'espree'
plugins:
  - vue
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
overrides:
  - files: tools/*.js
    rules:
      '@typescript-eslint/no-var-requires': 'off'
