version: '3'
name: cloud-board

services:
  db:
    container_name: cloud-board-db
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: cloud
      MARIADB_PASSWORD: board
    volumes:
      - cloud-board-data:/var/lib/mysql

  db-adminer:
    container_name: cloud-board-db-adminer
    image: adminer
    restart: always
    ports:
      - 3300:8080
    environment:
      ADMINER_DESIGN: hydra
      ADMINER_DEFAULT_SERVER: cloud-board-db
    depends_on:
      - db

  server:
    container_name: cloud-board-server
    build:
      context: .
      dockerfile: dockerfile.server
      target: development
    volumes:
      - .:/home/app
    ports:
      - 3030:80
    environment:
      MONGODB_URI: mongodb://cloud-board:cloud-board@cloud-board-db:27017/cloud-board
    depends_on:
      - db

  client:
    container_name: cloud-board-client
    build:
      context: .
      dockerfile: dockerfile.client
      target: development
    volumes:
      - .:/home/app
    ports:
      - 3000:80
    depends_on:
      - server

  monitor:
    container_name: cloud-board-monitor
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3003:8080

volumes:
  cloud-board-data:
