version: '3'
name: cloud-board

services:
  db:
    container_name: cloud-board-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  db-adminer:
    container_name: cloud-board-db-adminer
    image: mongo-express
    restart: always
    ports:
      - 3333:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@cloud-board-db:27017/
    depends_on:
      - db

  server:
    container_name: cloud-board-server
    build:
      context: .
      dockerfile: dockerfile.server
      target: development
    volumes:
      - .:/home/app
    ports:
      - 3030:80
    environment:
      MONGODB_URI: mongodb://api:api@cloud-board-db:27017/cloud-board
    depends_on:
      - db

  client:
    container_name: cloud-board-client
    build:
      context: .
      dockerfile: dockerfile.client
      target: development
    volumes:
      - .:/home/app
    ports:
      - 3000:80
    depends_on:
      - server

  monitor:
    container_name: cloud-board-monitor
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3003:8080
