FROM node:16.17.0-alpine AS base
WORKDIR /home/app

FROM base AS dependencies
COPY tools tools
COPY package.json package.json
RUN yarn

FROM base AS config
ARG PORT=80
EXPOSE ${PORT}
ENV PORT ${PORT}

FROM config AS development
COPY --from=dependencies /home/app/node_modules node_modules
COPY . .
CMD ["yarn", "dev:server"]

FROM base AS production
RUN echo "Please use the `dockerfile.production` for a development build."; exit 1